twig:
    file_name_pattern: '*.twig'
    globals:
        onboarding_language: '@App\Onboarding\OnboardingLanguageContext'
        viewer_context: '@App\Onboarding\ViewerContext'

when@test:
    twig:
        strict_variables: true
