knp_paginator:
    convert_exception: false
    page_range: 4
    remove_first_page_param: true
    default_options:
        page_name: page
        sort_field_name: sort
        sort_direction_name: direction
        distinct: true
        page_out_of_range: fix
        default_limit: 9
    template:
        pagination: 'pagination/hirely_pagination.html.twig'
