<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSL1qH5M\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSL1qH5M/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSL1qH5M.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSL1qH5M\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSL1qH5M\App_KernelDevDebugContainer([
    'container.build_hash' => 'SL1qH5M',
    'container.build_id' => 'f1d18b83',
    'container.build_time' => 1775740525,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSL1qH5M');
